packages:
  - ./apps
  - ./apps/pages

overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  '@eslint/eslintrc>minimatch': ^3.1.2
  '@eslint/js': '>=10'
  '@stylistic/eslint-plugin': '>=5.0.0'
  eslint: '>=10'
  minimatch@<10.2.1: '>=10.2.1'